# Generated by Django 3.2.9 on 2022-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_list',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
